backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img"
public_folder: "/img"

media_library:
  name: uploadcare

collections:
  - name: "test"
    label: "Test"
    folder: "site/content/test"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}