backend:
  name: git-gateway
  branch: main  # Change this to the branch you're using

media_folder: "site/static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "site/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
