backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

media_library:
  name: uploadcare

collections:
  - name: "post"
    label: "Post"
    folder: "site/content/post"
    path: "{{slug}}/index"
    create: true
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Intro Blurb", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }